import { describe, it, expect, beforeEach } from 'vitest';
import * as fc from 'fast-check';
import { createAIAssistantStore } from './ai-assistant-store';

/**
 * Arbitrary for a valid AIHistoryRecord input (without id and timestamp,
 * which are auto-generated by addHistoryRecord).
 */
const historyRecordInputArb = fc.record({
  projectId: fc.constant('test-project'),
  skillLabel: fc.string({ minLength: 1, maxLength: 20 }),
  userInput: fc.string({ minLength: 1, maxLength: 50 }),
  generatedContent: fc.string({ minLength: 1, maxLength: 100 }),
});

/**
 * Feature: comprehensive-quality-audit, Property 16: AI 历史记录上限约束
 * Validates: Requirements 17.1
 *
 * 对于任意数量的 addHistoryRecord 调用，listHistory 返回的记录数不应超过 50 条。
 */
describe('Property 16: AI 历史记录上限约束', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  it('listHistory 返回的记录数不应超过 50 条', () => {
    fc.assert(
      fc.property(
        // Generate between 40 and 80 records to add
        fc.integer({ min: 40, max: 80 }),
        fc.array(historyRecordInputArb, { minLength: 80, maxLength: 80 }),
        (count, records) => {
          localStorage.clear();
          const store = createAIAssistantStore();
          const projectId = 'test-project';

          // Add `count` records
          for (let i = 0; i < count; i++) {
            store.addHistoryRecord(projectId, records[i]);
          }

          const history = store.listHistory(projectId);

          // Core property: never exceeds 50
          expect(history.length).toBeLessThanOrEqual(50);

          // Also verify the exact expected count
          const expectedCount = Math.min(count, 50);
          expect(history.length).toBe(expectedCount);
        },
      ),
      { numRuns: 100 },
    );
  });
});

/**
 * Feature: comprehensive-quality-audit, Property 17: AI 历史记录时间倒序
 * Validates: Requirements 17.4
 *
 * 对于任意项目的历史记录，listHistory 返回的记录应按 timestamp 降序排列（最新的在前）。
 */
describe('Property 17: AI 历史记录时间倒序', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  it('listHistory 返回的记录按 timestamp 降序排列', () => {
    fc.assert(
      fc.property(
        // Generate between 2 and 30 records
        fc.array(historyRecordInputArb, { minLength: 2, maxLength: 30 }),
        (records) => {
          localStorage.clear();
          const store = createAIAssistantStore();
          const projectId = 'test-project';

          // Add all records sequentially
          for (const record of records) {
            store.addHistoryRecord(projectId, record);
          }

          const history = store.listHistory(projectId);

          // Verify descending timestamp order (newest first)
          for (let i = 0; i < history.length - 1; i++) {
            const current = new Date(history[i].timestamp).getTime();
            const next = new Date(history[i + 1].timestamp).getTime();
            expect(current).toBeGreaterThanOrEqual(next);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
